<?xml version="1.0" encoding="utf-8"?>
<!--
    Copyright (c) 2018-2022 Qualcomm Technologies, Inc.
    All Rights Reserved.
    Confidential and Proprietary - Qualcomm Technologies, Inc.

    Not a Contribution.

    Copyright (C) 2012-2018 The Linux Foundation. All rights reserved.
    Copyright (C) 2012-2013 The Android Open Source Project

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!--
<!DOCTYPE MediaCodecs [
<!ELEMENT Include EMPTY>
<!ATTLIST Include href CDATA #REQUIRED>
<!ELEMENT MediaCodecs (Decoders|Encoders|Include)*>
<!ELEMENT Decoders (MediaCodec|Include)*>
<!ELEMENT Encoders (MediaCodec|Include)*>
<!ELEMENT MediaCodec (Type|Quirk|Include)*>
<!ATTLIST MediaCodec name CDATA #REQUIRED>
<!ATTLIST MediaCodec type CDATA>
<!ELEMENT Type EMPTY>
<!ATTLIST Type name CDATA #REQUIRED>
<!ELEMENT Quirk EMPTY>
<!ATTLIST Quirk name CDATA #REQUIRED>
]>

There's a simple and a complex syntax to declare the availability of a
media codec:

A codec that properly follows the OpenMax spec and therefore doesn't have any
quirks and that only supports a single content type can be declared like so:

    <MediaCodec name="OMX.foo.bar" type="something/interesting" />
-->
<!--
 Non-Secure decoder capabilities
 (MB is defined as 16x16)
  _______________________________________________________
 | Codec       |  W        H    fps     Mbps     MB/s    |
 |_____________|_________________________________________|
 | h264        | 1920    1088    60      60     489600   |
 | hevc        | 1920    1088    60      60     489600   |
 | vp9         | 1920    1088    60      60     489600   |
 |_____________|_________________________________________|

 Secure decoder capabilities
 (MB is defined as 16x16)
_____________________________________________________
 | Codec    |   W      H     fps     Mbps      MB/s   |
 |__________|_________________________________________|
 | h264     | 1920    1088    60      35      489600  |
 | vp9      | 1920    1088    60      35      489600  |
 | hevc     | 1920    1088    60      35      489600  |
 |__________|_________________________________________|


 Non-Secure encoder capabilities (Secure not supported)
 (MB is defined as 16x16)
 ______________________________________________________
 | Codec    | W       H      fps     Mbps     MB/s    |
 |__________|_________________________________________|
 | h264     | 1920    1088    60      60     489600   |
 | hevc     | 1920    1088    60      60     489600   |
 |__________|_________________________________________|
-->

<MediaCodecs>
    <Include href="media_codecs_google_audio.xml" />
    <Include href="media_codecs_vendor_audio.xml" />
    <Include href="media_codecs_google_telephony.xml" />
    <Include href="media_codecs_c2_audio.xml" />
    <Settings>
        <Setting name="max-video-encoder-input-buffers" value="11" />
    </Settings>
    <Settings>
        <Variant name="slow-cpu" enabled="true" />
    </Settings>
    <Decoders>
       <!-- C2 decoders  -->
        <MediaCodec name="c2.qti.avc.decoder" type="video/avc" >
            <Alias name="OMX.qcom.video.decoder.avc"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" range="36-489600" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-120" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Limit name="concurrent-instances" max="16" />
            <Limit name="performance-point-1920x1080" value="60" />
            <Limit name="performance-point-1280x720" value="120" />
        </MediaCodec>
        <MediaCodec name="c2.qti.avc.decoder.low_latency" type="video/avc">
            <Alias name="OMX.qcom.video.decoder.avc.low_latency"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" range="36-489600" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-120" />
            <Limit name="concurrent-instances" max="16" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Feature name="low-latency" />
            <Limit name="concurrent-instances" max="16" />
            <Limit name="performance-point-1920x1080" value="60" />
            <Limit name="performance-point-1280x720" value="120" />
        </MediaCodec>
        <MediaCodec name="c2.qti.avc.decoder.secure" type="video/avc" >
            <Alias name="OMX.qcom.video.decoder.avc.secure"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="36" max="489600" />
            <Limit name="bitrate" range="1-35000000" />
            <Limit name="frame-rate" range="1-60" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Feature name="low-latency" />
            <Feature name="secure-playback" required="true" />
            <Limit name="concurrent-instances" max="3" />
            <Limit name="concurrent-instances" max="3" />
            <Limit name="performance-point-1920x1080" value="30" />
        </MediaCodec>
        <MediaCodec name="c2.qti.hevc.decoder" type="video/hevc" >
            <Alias name="OMX.qcom.video.decoder.hevc"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="36" max="489600" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-120" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Limit name="concurrent-instances" max="16" />
            <Limit name="performance-point-1920x1080" value="60" />
            <Limit name="performance-point-1280x720" value="120" />
        </MediaCodec>
        <MediaCodec name="c2.qti.hevc.decoder.low_latency" type="video/hevc" >
            <Alias name="OMX.qcom.video.decoder.hevc.low_latency"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="36" max="489600" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-120" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Feature name="low-latency" />
            <Limit name="concurrent-instances" max="16" />
            <Limit name="performance-point-1920x1080" value="60" />
            <Limit name="performance-point-1280x720" value="120" />
        </MediaCodec>
        <MediaCodec name="c2.qti.hevc.decoder.secure" type="video/hevc" >
            <Alias name="OMX.qcom.video.decoder.hevc.secure"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="36" max="489600" />
            <Limit name="bitrate" range="1-35000000" />
            <Limit name="frame-rate" range="1-60" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Feature name="low-latency" />
            <Feature name="secure-playback" required="true" />
            <Limit name="concurrent-instances" max="3" />
            <Limit name="performance-point-1920x1080" value="30" />
        </MediaCodec>
        <MediaCodec name="c2.qti.vp9.decoder" type="video/x-vnd.on2.vp9" >
            <Alias name="OMX.qcom.video.decoder.vp9"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="36" max="489600" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-60" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Limit name="concurrent-instances" max="6" />
            <Limit name="performance-point-1920x1080" value="60" />
        </MediaCodec>
        <MediaCodec name="c2.qti.vp9.decoder.secure" type="video/x-vnd.on2.vp9" >
            <Alias name="OMX.qcom.video.decoder.vp9.secure"/>
            <Limit name="size" min="96x96" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="36" max="489600" />
            <Limit name="bitrate" range="1-35000000" />
            <Limit name="frame-rate" range="1-60" />
            <Feature name="adaptive-playback" />
            <Feature name="can-swap-width-height" required="true" />
            <Feature name="secure-playback" required="true" />
            <Limit name="concurrent-instances" max="3" />
            <Limit name="performance-point-1920x1080" value="30" />
        </MediaCodec>
        <MediaCodec name="c2.android.av1.decoder" type="video/av01" update="true" variant="slow-cpu">
            <Limit name="size" min="96x96" max="1920x1080" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="24" max="2073600" />
            <Limit name="bitrate" range="1-120000000" />
            <Limit name="frame-rate" range="1-60" />
            <Feature name="adaptive-playback" />
        </MediaCodec>
        <MediaCodec name="c2.android.hevc.decoder" type="video/hevc" update="true">
            <!-- profiles and levels:  ProfileMain : MainTierLevel51 -->
            <Limit name="size" min="2x2" max="1280x720" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="8x8" />
            <Limit name="block-count" range="1-3600" />
            <Limit name="blocks-per-second" range="1-108000" />
            <Limit name="bitrate" range="1-2000000" />
       </MediaCodec>
       <MediaCodec name="c2.android.avc.decoder" type="video/avc" update="true">
            <!-- profiles and levels:  ProfileHigh : Level51 -->
            <Limit name="size" min="2x2" max="1280x720" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="block-count" range="1-3600" />
            <Limit name="blocks-per-second" range="1-108000" />
            <Limit name="bitrate" range="1-20000000" />
            <Feature name="adaptive-playback" />
       </MediaCodec>
    </Decoders>
    <Encoders>
        <!-- C2 Encoders -->
        <MediaCodec name="c2.qti.avc.encoder" type="video/avc">
            <Alias name="OMX.qcom.video.encoder.avc"/>
            <Limit name="size" min="128x128" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="64" max="489600" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-120" />
            <Limit name="concurrent-instances" max="16" />
            <Feature name="intra-refresh" />
            <Feature name="can-swap-width-height" required="true" />
            <Feature name="bitrate-modes" value="VBR,CBR" />
            <Limit name="performance-point-1920x1080" value="60" />
            <Limit name="performance-point-1280x720" value="120" />
        </MediaCodec>
        <MediaCodec name="c2.qti.hevc.encoder" type="video/hevc">
            <Alias name="OMX.qcom.video.encoder.hevc"/>
            <Limit name="size" min="128x128" max="1920x1088" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="64" max="489600" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-120" />
            <Limit name="concurrent-instances" max="16" />
            <Feature name="bitrate-modes" value="VBR,CBR" />
            <Feature name="intra-refresh" />
            <Feature name="can-swap-width-height" required="true" />
            <Limit name="performance-point-1920x1080" value="60" />
            <Limit name="performance-point-1280x720" value="120" />
        </MediaCodec>
        <MediaCodec name="c2.qti.hevc.encoder.cq" type="video/hevc">
            <Alias name="OMX.qcom.video.encoder.hevc.cq"/>
            <Limit name="size" min="128x128" max="512x512" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="64" max="786432" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-120" />
            <Limit name="concurrent-instances" max="16" />
            <Limit name="quality" range="0-100" default="80" />
            <Feature name="bitrate-modes" value="CQ" />
            <Limit name="performance-point-512x512" value="2025" />
        </MediaCodec>
        <MediaCodec name="c2.qti.heic.encoder" type="image/vnd.android.heic">
            <Alias name="OMX.qcom.video.encoder.heic"/>
            <Limit name="size" min="512x512" max="8192x8192" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="16x16" />
            <Limit name="blocks-per-second" min="64" max="786432" />
            <Limit name="bitrate" range="1-60000000" />
            <Limit name="frame-rate" range="1-20" />
            <Limit name="concurrent-instances" max="6" />
            <Limit name="quality" range="0-100" default="80" />
            <Feature name="bitrate-modes" value="CQ" />
            <Limit name="performance-point-8192x4320" value="3" />
            <Limit name="performance-point-1920x1080" value="6" />
        </MediaCodec>
        <MediaCodec name="c2.android.hevc.encoder" type="video/hevc" update="true" variant="slow-cpu">
            <!-- profiles and levels:  ProfileMain : MainTierLevel51 -->
            <Limit name="size" min="2x2" max="512x512" />
            <Limit name="alignment" value="2x2" />
            <Limit name="block-size" value="8x8" />
            <Limit name="block-count" range="1-4096" /> <!-- max 512x512 -->
            <Limit name="blocks-per-second" range="1-122880" />
            <Limit name="frame-rate" range="1-120" />
            <Limit name="bitrate" range="1-10000000" />
            <Limit name="complexity" range="0-10"  default="0" />
            <Limit name="quality" range="0-100"  default="80" />
            <Feature name="bitrate-modes" value="VBR,CBR,CQ" />
        </MediaCodec>
    </Encoders>
    <Include href="media_codecs_google_c2.xml" />
</MediaCodecs>
